### ISSUE TITLE
Handle payment exception and show customer human readable error message

### ISSUE THREAD

**Issue by fernandosjp** [amigosdapoli/donation-system#36]

**Comment by ricardo-numakura** [comment]
When processing gateway transaction response, process responseCode:
- 0 = approved
- 1 = denied
- 2 = denied for fraud/duplicity
- 5 = Being manually analyzed for fraud
- 1022 = Card operator error
- 1024 = Error in sent parameters
- 1025 = Credential error
- 2048 = Internal MaxiPago error
- 4097 = card acquirer timeout

**Comment by ricardo-numakura** [comment]
Single field errors:
Validate phone number and return error message if invalid.
Change e-mail and CPF error message format to become more visible.

**Comment by ricardo-numakura** [comment]
I'm considering removing PaymentTransaction model altogether and copy payment form from the following link. No credit card info is saved in server and all data is validated. 
https://www.djangosnippets.org/snippets/907/

**Comment by fernandosjp** [comment]
I added validation if credit card number is different than 16 numbers already showing message at the top of the page.
