### ISSUE TITLE
Integrate important development tools to GitHub repo

### ISSUE THREAD

**Issue by fernandosjp** [amigosdapoli/donation-system#85]
- Travis ci 
- code coverage (caveralls or codecov)
- code climate

**Comment by amigosdapoli-admin** [comment]
caveralls or codecov

**Comment by fernandosjp** [comment]
Travis CI for dbwrapper unite tests running.
Still needs to add funcional tests.

**Comment by fernandosjp** [comment]
Code climate integrated

**Comment by fernandosjp** [comment]
https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage

**Comment by fernandosjp** [comment]
Test coverage integrated using covarage.py and Code Climate. 
Only thing missing to close issue is make funcional tests with Geckodriver and Selenium work on Travis CI

**Comment by fernandosjp** [comment]
Code climate and travis CI working
